import streamlit as st
import pandas as pd
import networkx as nx
from pyvis.network import Network
from pathlib import Path
import tempfile


# ============================================================
# CONFIG
# ============================================================

BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "output"

ALERTS_FILE = OUTPUT_DIR / "alerts.csv"
EXPLAINED_FILE = OUTPUT_DIR / "alerts_explained.csv"

# GraphML generated by entity_graph_modified.py
GRAPHML_FILE = OUTPUT_DIR / "entity_graph_full.graphml"

# Fallback HTML
GRAPH_HTML_FILE = OUTPUT_DIR / "entity_graph_full_focused.html"

# --------------------------------------------------------------
# Single source of truth for tier -> color, used everywhere a tier
# is drawn (metrics, table, graph nodes) so the same tier is never
# two different colors in two different places. Only the three
# tiers build_alerts.py actually produces -- no "critical", it
# doesn't exist in this pipeline.
# --------------------------------------------------------------
TIER_COLORS = {
    "high": "#B23A3A",
    "medium-high": "#C97A2B",
    "worth reviewing": "#A88A2A",
    "none": "#8A94A6",
}
# Graph canvas stays navy, matching the slide's palette -- a dark
# "console" panel for the investigation graph is a deliberate,
# common pattern in security tooling (dense, colored nodes read
# better on a dark canvas), not a leftover from a forced dark mode.
# The surrounding page itself is light, per .streamlit/config.toml.
GRAPH_BG_COLOR = "#111C33"
NAVY = "#1B2A4A"
ACCENT_COLOR = "#3D6FB4"


# ============================================================
# PAGE
# ============================================================

st.set_page_config(
    page_title="CyberStrix Investigator",
    page_icon=":mag:",
    layout="wide",
)


# ============================================================
# LOAD DATA
# ============================================================


@st.cache_data
def load_data():

    alerts = pd.read_csv(ALERTS_FILE)
    explained = pd.read_csv(EXPLAINED_FILE)

    return alerts, explained


try:
    alerts, explained = load_data()

except Exception as e:
    st.error(f"Could not load output files: {e}")
    st.stop()


@st.cache_resource
def load_graph():
    """Load the full IP -> Transaction -> Wallet GraphML once."""
    if not GRAPHML_FILE.exists():
        return None

    try:
        return nx.read_graphml(GRAPHML_FILE)
    except Exception as e:
        st.error(f"Could not load entity graph: {e}")
        return None


G = load_graph()


# ============================================================
# GRAPH FUNCTIONS
# ============================================================


def find_transaction_node(G, txid):
    """
    Find the transaction node corresponding to the selected TXID.
    Handles different node-id/label formats.
    """

    txid = str(txid)

    for node, data in G.nodes(data=True):
        node_text = str(node)

        label = str(data.get("label", ""))

        node_type = str(data.get("node_type", "")).lower()

        if txid == node_text:
            return node

        if txid in label:
            return node

        # Transaction nodes in our graph normally contain TX
        if node_type == "transaction" and txid in node_text:
            return node

    return None


def build_investigation_graph(txid, wallet_id):

    if not GRAPHML_FILE.exists():
        return None

    try:
        G = nx.read_graphml(GRAPHML_FILE)

    except Exception as e:
        st.error(f"Could not read entity graph: {e}")
        return None

    tx_node = find_transaction_node(G, txid)

    if tx_node is None:
        return None

    # --------------------------------------------------------
    # Find the wallet belonging to this alert
    # --------------------------------------------------------

    wallet_node = None
    wallet_id_text = str(wallet_id)

    for node, data in G.nodes(data=True):
        node_id = str(node)
        label = str(data.get("label", ""))

        node_type = str(data.get("node_type", data.get("type", ""))).lower()

        combined = (node_id + " " + label).lower()

        if "wallet" in node_type:
            # Prefer an exact Wallet #ID match.
            if (
                f"wallet #{wallet_id_text}".lower() in combined
                or f"wallet_{wallet_id_text}".lower() in combined
                or f"wallet-{wallet_id_text}".lower() in combined
            ):
                wallet_node = node
                break

    # --------------------------------------------------------
    # Build the investigation neighborhood
    # --------------------------------------------------------

    nodes_to_keep = {tx_node}

    # Direct transaction connections
    nodes_to_keep.update(G.neighbors(tx_node))

    # Explicitly include the wallet associated with the alert
    if wallet_node is not None:
        nodes_to_keep.add(wallet_node)

        # Wallet's direct connections
        nodes_to_keep.update(G.neighbors(wallet_node))

        # Incoming connections for directed graphs
        if G.is_directed():
            nodes_to_keep.update(G.predecessors(wallet_node))

    investigation_G = G.subgraph(nodes_to_keep).copy()

    # --------------------------------------------------------
    # Make TX -> Wallet relationship visible if it is absent
    # --------------------------------------------------------

    if wallet_node is not None:
        if not (
            investigation_G.has_edge(tx_node, wallet_node)
            or investigation_G.has_edge(wallet_node, tx_node)
        ):
            investigation_G.add_edge(tx_node, wallet_node, label="belongs_to_wallet")

    return investigation_G


def n_hop_query(G, entity, hops=2):
    entity = str(entity)

    if entity not in G:
        for node, data in G.nodes(data=True):
            if (
                str(data.get("label", "")) == entity
                or str(data.get("wallet_id", "")) == entity
                or str(node).endswith(entity)
            ):
                entity = node
                break
        else:
            return None

    lengths = nx.single_source_shortest_path_length(
        G.to_undirected(), entity, cutoff=hops
    )

    return G.subgraph(lengths.keys()).copy()


def shortest_path_query(G, entity_a, entity_b):
    """Find shortest relationship path between two entities."""

    def resolve_entity(entity):
        entity = str(entity)

        if entity in G:
            return entity

        for node, data in G.nodes(data=True):
            if (
                str(data.get("label", "")) == entity
                or str(data.get("wallet_id", "")) == entity
                or str(node).endswith(entity)
            ):
                return node

        return None

    entity_a = resolve_entity(entity_a)
    entity_b = resolve_entity(entity_b)

    if entity_a is None or entity_b is None:
        return None

    try:
        return nx.shortest_path(G.to_undirected(), entity_a, entity_b)
    except nx.NetworkXNoPath:
        return None


def get_path_subgraph(G, path):
    """Create a graph containing only the nodes/edges in a path."""
    if not path or len(path) < 2:
        return None

    return G.subgraph(path).copy()


def fund_flow_query(G, entity, hops=2, direction="both"):
    entity = str(entity).strip()

    # Resolve wallet/entity ID to actual graph node
    if entity not in G:
        for node, data in G.nodes(data=True):
            if (
                str(data.get("wallet_id", "")) == entity
                or str(data.get("label", "")) == entity
                or str(node) == f"wallet:{entity}"
            ):
                entity = node
                break
        else:
            return None

    if direction == "outgoing":
        search_graph = G
    elif direction == "incoming":
        search_graph = G.reverse()
    else:
        search_graph = G.to_undirected()

    lengths = nx.single_source_shortest_path_length(search_graph, entity, cutoff=hops)

    return G.subgraph(lengths.keys()).copy()


def render_investigation_graph(G, selected_txid):

    net = Network(
        height="650px",
        width="100%",
        bgcolor=GRAPH_BG_COLOR,
        font_color="#e6e8ec",
        directed=True,
    )

    net.set_options(
        """
        {
          "physics": {
            "enabled": true,
            "stabilization": {
              "iterations": 200
            }
          },
          "interaction": {
            "hover": true,
            "navigationButtons": true,
            "keyboard": true
          },
          "edges": {
            "arrows": {
              "to": {
                "enabled": true
              }
            },
            "smooth": {
              "enabled": true
            }
          }
        }
        """
    )

    # --------------------------------------------------------
    # Add nodes
    # --------------------------------------------------------

    # Computed ONCE per render call, not per-node inside the loop below --
    # rescanning the whole graph for every single node just to check "is
    # this the highlighted one" is O(n^2) and only gets away with it at
    # small focused-subgraph sizes.
    highlighted_node = str(find_transaction_node(G, selected_txid))

    for node, data in G.nodes(data=True):
        node_id = str(node)

        label = str(data.get("label", node_id))

        node_type = str(data.get("node_type", data.get("type", ""))).lower()

        # Determine node type from label/id if needed
        if not node_type:
            if "tx" in label.lower():
                node_type = "transaction"

            elif "wallet" in label.lower():
                node_type = "wallet"

            else:
                node_type = "ip"

        # ----------------------------------------------------
        # Colors
        # ----------------------------------------------------

        if node_id == highlighted_node:
            color = "#e8564f"
            size = 35

        elif node_type == "transaction":
            color = TIER_COLORS.get(
                str(data.get("priority_tier", "")).lower(), "#8a90a3"
            )
            size = 25

        elif node_type == "wallet":
            # Alerted wallets are colored by tier, normal counterparties
            # neutral grey-blue. NOTE: wallet nodes carry their tier under
            # "max_priority_tier" (a wallet can have several alerted
            # transactions; this is the worst one) -- entity_graph.py only
            # ever sets a plain "priority_tier" on TRANSACTION nodes.
            # Reading "priority_tier" here always misses on wallet nodes,
            # so every wallet silently fell through to the same color
            # regardless of alert status.
            priority = str(data.get("max_priority_tier", "")).lower()
            color = TIER_COLORS.get(priority, "#6f9bd1")
            size = 22

        else:
            # IP
            color = ACCENT_COLOR
            size = 17

        # ----------------------------------------------------
        # Tooltip
        # ----------------------------------------------------

        tooltip = f"""
        <b>{label}</b><br>
        Type: {node_type}
        """

        if "risk_score" in data:
            tooltip += f"<br>Risk score: {data['risk_score']}"

        if "priority_tier" in data:
            tooltip += f"<br>Priority: {data['priority_tier']}"

        if "max_priority_tier" in data:
            tooltip += f"<br>Worst alert tier: {data['max_priority_tier']}"

        net.add_node(
            node_id,
            label=label,
            title=tooltip,
            color=color,
            size=size,
        )

    # --------------------------------------------------------
    # Add edges
    # --------------------------------------------------------

    for source, target, data in G.edges(data=True):
        edge_label = str(
            data.get("label", data.get("relationship", data.get("type", "")))
        )

        net.add_edge(
            str(source),
            str(target),
            title=edge_label,
            label=edge_label if edge_label else "",
            color="#3a3f4b",
        )

    # --------------------------------------------------------
    # Generate HTML
    # --------------------------------------------------------

    with tempfile.NamedTemporaryFile(delete=False, suffix=".html") as temp:
        temp_path = temp.name

    net.write_html(
        temp_path,
        notebook=False,
        open_browser=False,
    )

    html = Path(temp_path).read_text(encoding="utf-8")

    return html


# ============================================================
# TITLE
# ============================================================

st.title("CyberStrix Investigator")

st.caption(
    "Offline Bitcoin transaction anomaly detection and investigation dashboard "
    "· runs fully offline, no network calls · synthetic demonstration data, "
    "not real seized evidence"
)


# ============================================================
# METRICS
# ============================================================

total_alerts = len(alerts)

# "critical" is not a tier build_alerts.py ever produces (only high /
# medium-high / worth reviewing) -- counting it in here was dead code.
high_alerts = len(alerts[alerts["priority_tier"] == "high"])

medium_alerts = len(alerts[alerts["priority_tier"] == "medium-high"])

both_alerts = len(alerts[alerts["detector"] == "both"])


col1, col2, col3, col4 = st.columns(4)

col1.metric("Total Alerts", total_alerts)

col2.metric("High Priority", high_alerts)

col3.metric("Medium-High", medium_alerts)

col4.metric("Flagged by Both Detectors", both_alerts)


st.divider()


# ============================================================
# SIDEBAR FILTERS
# ============================================================

st.sidebar.header("Investigation Filters")

priority_options = sorted(alerts["priority_tier"].dropna().unique())

selected_priority = st.sidebar.multiselect(
    "Priority",
    priority_options,
    default=priority_options,
)

detector_options = sorted(alerts["detector"].dropna().unique())

selected_detector = st.sidebar.multiselect(
    "Detector",
    detector_options,
    default=detector_options,
)


filtered = alerts[
    alerts["priority_tier"].isin(selected_priority)
    & alerts["detector"].isin(selected_detector)
].copy()


# ============================================================
# ALERT TABLE
# ============================================================

st.header("Investigation Alerts")

st.write(f"Showing **{len(filtered)}** of **{len(alerts)}** alerts.")

display_columns = [
    "txid",
    "canonical_wallet_id",
    "detector",
    "priority_tier",
    "xgb_proba",
    "if_score",
]

table = filtered[display_columns].copy()

table["xgb_proba"] = table["xgb_proba"].round(4)

table["if_score"] = table["if_score"].round(4)

st.dataframe(
    table,
    width='stretch',
    hide_index=True,
)


# ============================================================
# INVESTIGATE ALERT
# ============================================================

st.divider()

st.header("Investigate Alert")

if len(filtered) == 0:
    st.warning("No alerts match the selected filters.")

else:
    selected_wallet_id = st.selectbox(
        "Select a wallet",
        sorted(
            filtered["canonical_wallet_id"].dropna().astype(str).unique(),
            key=lambda x: int(float(x)) if x.replace(".", "", 1).isdigit() else x,
        ),
    )

    wallet_filtered = filtered[
        filtered["canonical_wallet_id"].astype(str) == selected_wallet_id
    ].copy()

    st.caption(
        f"Wallet **#{selected_wallet_id}** has "
        f"**{len(wallet_filtered)} alert(s)** matching the current filters."
    )

    selected_txid = st.selectbox(
        "Select a transaction for this wallet", wallet_filtered["txid"].tolist()
    )

    #
    selected = explained[explained["txid"] == selected_txid]

    if len(selected) == 0:
        st.warning("No explanation data is available for this transaction.")

    else:
        row = selected.iloc[0]

        # ----------------------------------------------------
        # Alert information
        # ----------------------------------------------------

        c1, c2, c3 = st.columns(3)

        c1.metric("Wallet ID", str(row["canonical_wallet_id"]))

        c2.metric("XGBoost Probability", f"{row['xgb_proba']:.2%}")

        c3.metric("Detector", str(row["detector"]))

        # ----------------------------------------------------
        # Priority
        # ----------------------------------------------------

        st.subheader("Alert Priority")

        priority = str(row["priority_tier"])

        if priority == "high":
            st.error("HIGH PRIORITY")

        elif priority == "medium-high":
            st.warning("MEDIUM-HIGH PRIORITY")

        else:
            st.info(priority.upper())

        # ----------------------------------------------------
        # Explanation
        # ----------------------------------------------------

        st.subheader("Why was it flagged?")

        st.info(str(row["top_reasons"]))

        # ----------------------------------------------------
        # SHAP
        # ----------------------------------------------------

        st.subheader("Top contributing features")

        feature_data = []

        for i in range(1, 4):
            feature = row.get(f"top_feature_{i}", None)

            shap_value = row.get(f"shap_{i}", None)

            if pd.notna(feature) and pd.notna(shap_value):
                feature_data.append(
                    {
                        "Feature": feature,
                        "SHAP Impact": float(shap_value),
                    }
                )

        if feature_data:
            shap_df = pd.DataFrame(feature_data)

            shap_df["SHAP Impact"] = shap_df["SHAP Impact"].round(4)

            st.dataframe(
                shap_df,
                width='stretch',
                hide_index=True,
            )

        # ----------------------------------------------------
        # Raw data
        # ----------------------------------------------------

        with st.expander("View raw alert data"):
            st.json({str(k): (None if pd.isna(v) else str(v)) for k, v in row.items()})

            # ====================================================
        # WALLET DOSSIER
        # ====================================================

        st.divider()
        st.header("Wallet Dossier")
        all_wallets = sorted(
            alerts["canonical_wallet_id"].dropna().astype(str).unique(),
            key=lambda x: int(x) if x.isdigit() else x,
        )

        dossier_wallet = st.selectbox(
            "Select Wallet",
            all_wallets,
            index=all_wallets.index(str(row["canonical_wallet_id"]))
            if str(row["canonical_wallet_id"]) in all_wallets
            else 0,
            key="dossier_wallet",
        )

        wallet_tx = alerts[
            alerts["canonical_wallet_id"].astype(str) == dossier_wallet
        ].copy()
        dossier_row = wallet_tx.iloc[0]

        st.caption(f"Investigation summary for Wallet #{dossier_wallet}")

        st.subheader("Investigation Summary")

        total_transactions = len(wallet_tx)

        unique_ips = set()

        for col in ["src_ip", "dst_ip"]:
            if col in wallet_tx.columns:
                unique_ips.update(wallet_tx[col].dropna().astype(str))

        d1, d2, d3, d4 = st.columns(4)

        d1.metric("Transactions", total_transactions)

        d2.metric("Unique IPs", len(unique_ips))

        d3.metric("Risk Score", f"{float(dossier_row.get('xgb_proba', 0)):.2%}")

        d4.metric("Detector", str(dossier_row.get("detector", "N/A")))

        st.write("**Associated IPs:**")

        if unique_ips:
            st.write(", ".join(list(unique_ips)[:10]))
        else:
            st.write("No IP data available")
        st.subheader("Transaction History")

        display_cols = [
            col
            for col in [
                "txid",
                "canonical_wallet_id",
                "sender",
                "receiver",
                "total_input_btc",
                "total_output_btc",
                "xgb_proba",
                "detector",
                "priority_tier",
            ]
            if col in wallet_tx.columns
        ]

        st.dataframe(wallet_tx[display_cols], width='stretch', hide_index=True)
        st.subheader("Network Associations")

        if unique_ips:
            network_data = pd.DataFrame({"IP Address": sorted(unique_ips)})

            st.dataframe(network_data, width='stretch', hide_index=True)
        else:
            st.info("No network associations found for this wallet.")

        # ====================================================
        # ALERT-SPECIFIC GRAPH
        # ====================================================

        st.divider()

        st.header("Investigation Graph")

        st.caption(
            "Showing the selected transaction "
            "and its directly connected IPs and wallets."
        )

        investigation_graph = build_investigation_graph(
            selected_txid, row["canonical_wallet_id"]
        )

        if investigation_graph is not None:
            st.write(
                f"**{len(investigation_graph.nodes)} "
                f"entities** connected to this transaction."
            )

            graph_html = render_investigation_graph(investigation_graph, selected_txid)

            st.iframe(
                graph_html,
                height=680,
                scrolling=False,
            )

        elif GRAPH_HTML_FILE.exists():
            st.info(
                "The selected transaction could not "
                "be isolated from the GraphML file. "
                "Showing the focused graph instead."
            )

            graph_html = GRAPH_HTML_FILE.read_text(encoding="utf-8")

            st.iframe(
                graph_html,
                height=680,
                scrolling=True,
            )

        else:
            st.warning("Entity graph not found. Run entity_graph_modified.py first.")


# ============================================================
# ADVANCED INVESTIGATION QUERIES
# ============================================================

st.divider()

st.header("Advanced Investigation")

if G is None:
    st.warning("Entity graph could not be loaded. Run entity_graph_modified.py first.")
else:
    tab1, tab2, tab3 = st.tabs(["N-Hop Analysis", "Wallet Path", "Fund Flow"])

    # --------------------------------------------------------
    # N-HOP ANALYSIS
    # --------------------------------------------------------

    with tab1:
        st.subheader("N-Hop Neighborhood")

        hop_entity = st.text_input(
            "Wallet / Entity",
            value=str(row["canonical_wallet_id"]) if "row" in locals() else "",
            key="hop_entity",
        )

        hop_count = st.slider(
            "Number of hops", min_value=1, max_value=5, value=2, key="hop_count"
        )

        if st.button("Run N-Hop Analysis", key="run_hop"):
            hop_graph = n_hop_query(G, hop_entity, hop_count)

            if hop_graph is None:
                st.error("Entity not found in graph.")

            else:
                st.success(
                    f"Found {hop_graph.number_of_nodes()} entities "
                    f"within {hop_count} hops."
                )

                hop_html = render_investigation_graph(
                    hop_graph, selected_txid if "selected_txid" in locals() else ""
                )

                st.iframe(hop_html, height=680, scrolling=False)

    # --------------------------------------------------------
    # SHORTEST PATH
    # --------------------------------------------------------

    with tab2:
        st.subheader("Shortest Relationship Path")

        wallet_a = st.text_input("Source Wallet", key="wallet_a")

        wallet_b = st.text_input("Destination Wallet", key="wallet_b")

        if st.button("Find Shortest Path", key="run_path"):
            path = shortest_path_query(G, wallet_a, wallet_b)

            if path is None:
                st.warning("No relationship path found between these two entities.")

            else:
                st.success(f"Path found: {len(path) - 1} hops")

                st.write(" → ".join(str(node) for node in path))

                path_graph = get_path_subgraph(G, path)

                path_html = render_investigation_graph(
                    path_graph, selected_txid if "selected_txid" in locals() else ""
                )

                st.iframe(path_html, height=680, scrolling=False)

    # --------------------------------------------------------
    # FUND FLOW
    # --------------------------------------------------------

    with tab3:
        st.subheader("Fund Flow Tracing")

        flow_entity = st.text_input(
            "Wallet / Entity",
            value=str(row["canonical_wallet_id"]) if "row" in locals() else "",
            key="flow_entity",
        )

        flow_hops = st.slider(
            "Tracing depth", min_value=1, max_value=5, value=2, key="flow_hops"
        )

        flow_direction = st.selectbox(
            "Direction", ["both", "outgoing", "incoming"], key="flow_direction"
        )

        if st.button("Trace Fund Flow", key="run_flow"):
            flow_graph = fund_flow_query(G, flow_entity, flow_hops, flow_direction)

            if flow_graph is None:
                st.error("Entity not found in graph.")

            else:
                st.success(
                    f"Found {flow_graph.number_of_nodes()} entities "
                    f"in the traced network."
                )

                flow_html = render_investigation_graph(
                    flow_graph, selected_txid if "selected_txid" in locals() else ""
                )

                st.iframe(flow_html, height=680, scrolling=False)


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "CyberStrix · Offline AI/ML investigation prototype · "
    "XGBoost + Isolation Forest + SHAP + Entity Graph"
)
