"""
Dataset B feature engineering + train/test split.

Ported from swathi/split_dataset.py (Dataset A pipeline) onto Dataset B
(Dataset(b)-f/output/, generated by the fee-leak-fixed generate_dataset.py).
Same causal, leak-safe feature logic — nothing about the methodology changed,
only the input/output paths, plus one addition: fee_ratio, which the original
script never computed even though it's the feature the leak was found in.
"""
import pandas as pd
import numpy as np
import json
import math
import random
import re
from collections import deque

random.seed(42)

# ---- Load raw data ----
raw = pd.read_csv('output/transactions.csv')
labels = pd.read_csv('output/ground_truth_labels.csv')
wallets_ref = pd.read_csv('output/wallets_reference.csv')

# ---- GeoIP enrichment (PS requirement: "integrate open source downloadable
# GeoIP database") ----
# Resolves src_ip -> real country/ASN via offline geoip2fast lookup, INDEPENDENT
# of the dataset's own baked-in geo_country/asn columns (those are synthetic
# ground-truth the generator used to shape wallet behavior, not derived from
# the IP). These resolved columns are added to `raw` for use by the entity
# graph's IP-node attributes and for reporting -- they are NOT swapped into
# the frozen FEATURE_COLS below. Doing that would change already-verified
# model behavior and needs an explicit decision, not a silent substitution.
from geoip_enrich import GeoEnricher
print("Resolving src_ip -> country/ASN via offline GeoIP (geoip2fast)...")
_geo = GeoEnricher()
raw = _geo.enrich_dataframe(raw, ip_col='src_ip',
                             country_col='geo_country_resolved',
                             asn_col='asn_resolved')
print(f"  Resolved {(~raw['asn_resolved'].isin(['UNRESOLVED'])).mean():.1%} of rows "
      f"(excl. UNRESOLVED; jittered IPs occasionally land outside the exact ASN block, expected)")

# ---- Parse list-columns ----
raw['input_list'] = raw['input_addresses'].apply(json.loads)
raw['output_list'] = raw['output_addresses'].apply(json.loads)
raw['input_amounts_list'] = raw['input_amounts'].apply(json.loads)
raw['output_amounts_list'] = raw['output_amounts'].apply(json.loads)

# ---- Structural features ----
raw['n_inputs'] = raw['input_list'].apply(len)
raw['n_outputs'] = raw['output_list'].apply(len)
raw['n_unique_input_addresses'] = raw['input_list'].apply(lambda x: len(set(x)))
raw['n_unique_output_addresses'] = raw['output_list'].apply(lambda x: len(set(x)))
raw['total_input_btc'] = raw['input_amounts_list'].apply(sum)
raw['total_output_btc'] = raw['output_amounts_list'].apply(sum)
raw['input_output_ratio'] = raw.apply(
    lambda row: row['total_input_btc'] / row['total_output_btc']
    if row['total_output_btc'] != 0 else 0,
    axis=1
)
raw['fan_in_5plus'] = (raw['n_inputs'] >= 5).astype(int)
raw['first_input_addr'] = raw['input_list'].apply(lambda x: x[0])
raw['output_min_max_ratio'] = raw['output_amounts_list'].apply(
    lambda amts: min(amts) / max(amts) if len(amts) > 1 and max(amts) > 0 else 1.0
)

# ---- fee_ratio: added for Dataset B ----
# fee / total_input_btc, guarded against div-by-zero. This is the exact feature
# the earlier leak was found in (hardcoded per-anomaly-type fee constants made
# this near-perfectly separable). Now that generate_dataset.py draws every fee
# from the same rand_fee_rate() distribution regardless of anomaly type, this
# should carry little to no signal on its own -- check.py verifies that.
raw['fee_ratio'] = raw.apply(
    lambda row: row['fee'] / row['total_input_btc'] if row['total_input_btc'] > 1e-12 else 0.0,
    axis=1
)

# ---- Behavioral / velocity features ----
# These are computed per-sender (first_input_addr), using ONLY that sender's transactions
# strictly BEFORE the current one (causal). This is what lets a single-transaction-row model
# see the same signal a wallet-level aggregation would see (burst frequency, IP/ASN churn,
# deviation from the sender's own running average) without collapsing rows into one-per-wallet.
#
# Why this matters: peeling_chain, wallet_reuse_burst, structuring, ip_hopping and
# profile_deviation are all defined by the generator as PATTERNS across a wallet's history,
# not by any single row's static shape (see generate_dataset.py's own comments). Without these
# columns, a per-transaction model is structurally blind to almost all of them.
raw['timestamp_dt'] = pd.to_datetime(raw['timestamp'], format='mixed', utc=True)

raw['sender_tx_count_1h'] = 0
raw['sender_tx_count_24h'] = 0
raw['sender_time_since_last_tx_min'] = -1.0
raw['sender_distinct_asn_last10'] = 0
raw['sender_distinct_ip_last10'] = 0
raw['sender_amount_zscore'] = 0.0

ONE_HOUR = pd.Timedelta('1h')
ONE_DAY = pd.Timedelta('24h')

for addr, idxs in raw.groupby('first_input_addr').groups.items():
    idxs = sorted(idxs, key=lambda i: raw.at[i, 'timestamp_dt'])
    recent_times = []       # pruned rolling history, all within the last 24h
    recent_asns = deque(maxlen=10)
    recent_ips = deque(maxlen=10)
    amounts_so_far = []      # this sender's amounts, all strictly BEFORE current row

    for i in idxs:
        t = raw.at[i, 'timestamp_dt']

        # drop history older than 24h so the window scans stay cheap and stay causal
        recent_times = [pt for pt in recent_times if t - pt <= ONE_DAY]

        raw.at[i, 'sender_tx_count_24h'] = len(recent_times)
        raw.at[i, 'sender_tx_count_1h'] = sum(1 for pt in recent_times if t - pt <= ONE_HOUR)
        raw.at[i, 'sender_time_since_last_tx_min'] = (
            (t - recent_times[-1]).total_seconds() / 60.0 if recent_times else -1.0
        )
        raw.at[i, 'sender_distinct_asn_last10'] = len(set(recent_asns))
        raw.at[i, 'sender_distinct_ip_last10'] = len(set(recent_ips))

        if len(amounts_so_far) >= 2:
            m, s = np.mean(amounts_so_far), np.std(amounts_so_far)
            # guard against near-zero std blowing this up to +/-1e15 when a sender's
            # past amounts happen to be nearly identical; clip to a sane range instead
            z = (raw.at[i, 'total_input_btc'] - m) / s if s > 1e-8 else 0.0
            raw.at[i, 'sender_amount_zscore'] = float(np.clip(z, -10, 10))
        else:
            raw.at[i, 'sender_amount_zscore'] = 0.0

        # NOW fold this transaction into history, so it can only affect FUTURE rows
        recent_times.append(t)
        recent_asns.append(raw.at[i, 'asn'])
        recent_ips.append(raw.at[i, 'src_ip'])
        amounts_so_far.append(raw.at[i, 'total_input_btc'])

# ---- Graph-linkage feature: was this row's sender address just created as
# someone's output? ----
# Peeling chains burn a brand-new address every hop (see generate_dataset.py:
# current_addr = change_addr), so every sender-history feature above is
# structurally blind to them -- the address has never been seen before, full
# stop. The only way to see this pattern is to follow the money: hop N's
# output becomes hop N+1's input. That's a graph edge (txn -> wallet -> txn),
# not a wallet-identity feature, computed here in GLOBAL time order (not
# grouped by sender, since the link crosses from one throwaway address to the
# next).
#
# Window = 3 hours: peeling-chain hops are 5-45 min apart (generator-enforced),
# comfortably inside this window. Normal wallets' own cadence is 30min-3days
# (regular) or 2-20min (merchant/exchange hard negatives) -- a regular wallet
# spending its own long-standing address shortly after receiving into it is
# rare but possible, so this feature is a strong, not perfect, signal. That's
# expected and fine -- it's real structural evidence, not a synthetic shortcut.
LINK_WINDOW = pd.Timedelta('3h')
raw_sorted_idx = raw.sort_values('timestamp_dt').index.tolist()

raw['input_addr_is_recent_output'] = 0
raw['minutes_since_addr_last_output'] = -1.0

last_output_time = {}  # address -> most recent timestamp it appeared as an output

for i in raw_sorted_idx:
    addr = raw.at[i, 'first_input_addr']
    t = raw.at[i, 'timestamp_dt']

    if addr in last_output_time:
        gap_min = (t - last_output_time[addr]).total_seconds() / 60.0
        raw.at[i, 'minutes_since_addr_last_output'] = gap_min
        if (t - last_output_time[addr]) <= LINK_WINDOW:
            raw.at[i, 'input_addr_is_recent_output'] = 1

    # NOW fold this row's outputs into the index, so it can only affect FUTURE rows
    for out_addr in raw.at[i, 'output_list']:
        last_output_time[out_addr] = t

feature_cols = [
    'txid', 'geo_country_resolved', 'asn_resolved',
    'n_inputs', 'n_outputs', 'n_unique_input_addresses',
    'n_unique_output_addresses', 'total_input_btc', 'total_output_btc',
    'input_output_ratio', 'fan_in_5plus', 'output_min_max_ratio', 'fee', 'fee_ratio',
    'input_addr_is_recent_output', 'minutes_since_addr_last_output',
    'first_input_addr',
    'sender_tx_count_1h', 'sender_tx_count_24h', 'sender_time_since_last_tx_min',
    'sender_distinct_asn_last10', 'sender_distinct_ip_last10', 'sender_amount_zscore',
]
featured = raw[feature_cols]

# ---- NaN/Inf check on the newly added / division-based columns ----
for col in ['fee_ratio', 'output_min_max_ratio', 'input_output_ratio']:
    n_nan = featured[col].isna().sum()
    n_inf = np.isinf(featured[col]).sum()
    if n_nan or n_inf:
        print(f"WARNING: {col} has {n_nan} NaN and {n_inf} Inf values")

# ---- Merge labels ----
df = featured.merge(labels[['txid', 'is_anomaly', 'anomaly_type', 'wallet_ids']], on='txid')
assert len(df) == len(featured), "Row count changed on merge - investigate before continuing"

# ---- Build canonical_wallet_id ----
addr_to_wallet_id = dict(zip(wallets_ref['address'], wallets_ref['wallet_id']))

def get_canonical_wallet_id(row):
    if row['is_anomaly'] == 0 or pd.isna(row['wallet_ids']):
        return addr_to_wallet_id.get(row['first_input_addr'])

    wid_str = str(row['wallet_ids'])
    patterns = [
        r'^synthetic_chain_(\d+)_hop',
        r'^mixer_(\d+)_',
        r'^burst_(\d+)$',
        r'^structuring_(\d+)$',
        r'^iphop_(\d+)$',
        r'^deviation_(\d+)$',
    ]
    for p in patterns:
        m = re.match(p, wid_str)
        if m:
            return int(m.group(1))
    return addr_to_wallet_id.get(row['first_input_addr'])

df['canonical_wallet_id'] = df.apply(get_canonical_wallet_id, axis=1)
missing_canonical = df['canonical_wallet_id'].isna().sum()
assert missing_canonical == 0, f"Missing canonical IDs: {missing_canonical}"
df['canonical_wallet_id'] = df['canonical_wallet_id'].astype(int)

TEST_FRACTION = 0.2
test_groups = set()

# ---- Step 1: for each anomaly type, force minimum wallet representation in test ----
anomaly_df = df[df['is_anomaly'] == 1]
print("=== Forcing test coverage per anomaly_type ===")
for atype in anomaly_df['anomaly_type'].unique():
    wallets = sorted(anomaly_df[anomaly_df['anomaly_type'] == atype]['canonical_wallet_id'].unique().tolist())
    n_test = max(1, math.ceil(len(wallets) * TEST_FRACTION))
    random.shuffle(wallets)
    chosen = wallets[:n_test]
    test_groups.update(chosen)
    print(f"  {atype}: {len(wallets)} unique wallets -> {n_test} forced into test")

# ---- Step 2: randomly split remaining groups (mostly normal-only) ----
all_groups = set(df['canonical_wallet_id'].unique())
remaining_groups = sorted(all_groups - test_groups)
random.shuffle(remaining_groups)

n_remaining_test = int(len(remaining_groups) * TEST_FRACTION)
test_groups.update(remaining_groups[:n_remaining_test])
train_groups = all_groups - test_groups

# ---- Assign rows ----
train_df = df[df['canonical_wallet_id'].isin(train_groups)].reset_index(drop=True)
test_df = df[df['canonical_wallet_id'].isin(test_groups)].reset_index(drop=True)

# ---- Verify no leakage ----
overlap = set(train_df['canonical_wallet_id']) & set(test_df['canonical_wallet_id'])
assert len(overlap) == 0, f"LEAKAGE: {len(overlap)} canonical wallets in both train and test"
assert len(train_df) + len(test_df) == len(df), "Row count mismatch after split"

# ---- Save ----
train_df.to_csv('output/train.csv', index=False)
test_df.to_csv('output/test.csv', index=False)

print(f"\nSplit complete, no leakage confirmed.")
print(f"Train shape: {train_df.shape}, anomaly rate: {train_df['is_anomaly'].mean():.4f}")
print(f"Test shape:  {test_df.shape}, anomaly rate: {test_df['is_anomaly'].mean():.4f}")
print(f"Train canonical wallets: {len(train_groups)}, Test canonical wallets: {len(test_groups)}, Canonical wallet overlap: {len(overlap)}")

print("\n=== anomaly_type coverage check (test set) ===")
for atype in anomaly_df['anomaly_type'].unique():
    n_train = (train_df['anomaly_type'] == atype).sum()
    n_test = (test_df['anomaly_type'] == atype).sum()
    print(f"  {atype}: train={n_train}, test={n_test}")